
# =========================
# SERVER
# =========================
server.port=8081


# =========================
# RABBITMQ CONFIG
# =========================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Listener (consumo de mensajes)
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=5

# Retry en caso de fallo procesando mensaje
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.retry.max-attempts=3


# =========================
# MONGODB CONFIG
# =========================
spring.data.mongodb.uri=mongodb://localhost:27017/deliveriesdb
spring.data.mongodb.database=deliveriesdb


# =========================
# LOGGING (opcional pero útil)
# =========================
logging.level.org.springframework.amqp=INFO
logging.level.org.springframework.data.mongodb=INFO
spring.application.name=msProof


management.endpoints.web.exposure.include=prometheus


